[versions]
agp = "8.6.1"
dokka = "2.0.0"
# backend
apimanager = "2.2.4"
json = "20250107"
jsoup = "1.18.1"
kotlinxSerializationJson = "1.8.1"
mysqlConnectorJava = "8.0.33"
spring= "3.2.3"
# core
equinox = "1.1.1"

[libraries]
dokka-base = { module = "org.jetbrains.dokka:dokka-base", version.ref = "dokka" }
# backend
apimanager = { module = "com.github.N7ghtm4r3:APIManager", version.ref = "apimanager" }
equinox-backend = { module = "io.github.n7ghtm4r3:equinox-backend", version.ref = "equinox" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
json = { module = "org.json:json", version.ref = "json" }
mysql-connector-java = { module = "mysql:mysql-connector-java", version.ref = "mysqlConnectorJava" }
spring-boot-maven-plugin = { module = "org.springframework.boot:spring-boot-maven-plugin", version.ref = "spring" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "spring" }
spring-boot-starter-thymeleaf = { module = "org.springframework.boot:spring-boot-starter-thymeleaf", version.ref = "spring" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring" }
# core
equinox-core = { module = "io.github.n7ghtm4r3:equinox-core", version.ref = "equinox" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }